//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Net/AcountLoginRequest.proto
namespace Net.AcountLoginRequest
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AcountLoginRequest")]
  public partial class AcountLoginRequest : global::ProtoBuf.IExtensible
  {
    public AcountLoginRequest() {}
    
    private string _accName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"accName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string accName
    {
      get { return _accName; }
      set { _accName = value; }
    }
    private string _ctoken = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ctoken", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ctoken
    {
      get { return _ctoken; }
      set { _ctoken = value; }
    }
    private string _pw = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"pw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pw
    {
      get { return _pw; }
      set { _pw = value; }
    }
    private string _pwr = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"pwr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string pwr
    {
      get { return _pwr; }
      set { _pwr = value; }
    }
    private string _cid = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cid
    {
      get { return _cid; }
      set { _cid = value; }
    }
    private string _deviceID = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"deviceID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceID
    {
      get { return _deviceID; }
      set { _deviceID = value; }
    }
    private int _zoneid = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"zoneid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int zoneid
    {
      get { return _zoneid; }
      set { _zoneid = value; }
    }
    private string _mac = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mac
    {
      get { return _mac; }
      set { _mac = value; }
    }
    private string _IDFA = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"IDFA", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string IDFA
    {
      get { return _IDFA; }
      set { _IDFA = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _type = "";
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _number = "";
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"number", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string number
    {
      get { return _number; }
      set { _number = value; }
    }
    private string _phoneMode = "";
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"phoneMode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phoneMode
    {
      get { return _phoneMode; }
      set { _phoneMode = value; }
    }
    private string _rsa = "";
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"rsa", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string rsa
    {
      get { return _rsa; }
      set { _rsa = value; }
    }
    private string _OS = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"OS", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string OS
    {
      get { return _OS; }
      set { _OS = value; }
    }
    private bool _quick = default(bool);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"quick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool quick
    {
      get { return _quick; }
      set { _quick = value; }
    }
    private string _facebookid = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"facebookid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string facebookid
    {
      get { return _facebookid; }
      set { _facebookid = value; }
    }
    private string _language = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"language", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string language
    {
      get { return _language; }
      set { _language = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}