//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Net/CarListMessage.proto
namespace Net.CarListMessage
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChipMessage")]
  public partial class ChipMessage : global::ProtoBuf.IExtensible
  {
    public ChipMessage() {}
    
    private int _chipId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"chipId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chipId
    {
      get { return _chipId; }
      set { _chipId = value; }
    }
    private int _chipLevel = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"chipLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chipLevel
    {
      get { return _chipLevel; }
      set { _chipLevel = value; }
    }
    private int _chipExp = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"chipExp", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chipExp
    {
      get { return _chipExp; }
      set { _chipExp = value; }
    }
    private int _chipSlot = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"chipSlot", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int chipSlot
    {
      get { return _chipSlot; }
      set { _chipSlot = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CarMessage")]
  public partial class CarMessage : global::ProtoBuf.IExtensible
  {
    public CarMessage() {}
    
    private int _car_id = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"car_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_id
    {
      get { return _car_id; }
      set { _car_id = value; }
    }
    private int _car_tmp_id = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"car_tmp_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_tmp_id
    {
      get { return _car_tmp_id; }
      set { _car_tmp_id = value; }
    }
    private int _car_color_RGB = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"car_color_RGB", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_color_RGB
    {
      get { return _car_color_RGB; }
      set { _car_color_RGB = value; }
    }
    private int _car_color = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"car_color", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_color
    {
      get { return _car_color; }
      set { _car_color = value; }
    }
    private int _car_power = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"car_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_power
    {
      get { return _car_power; }
      set { _car_power = value; }
    }
    private int _car_s_power = default(int);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"car_s_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_s_power
    {
      get { return _car_s_power; }
      set { _car_s_power = value; }
    }
    private int _car_mt_power = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"car_mt_power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_mt_power
    {
      get { return _car_mt_power; }
      set { _car_mt_power = value; }
    }
    private int _car_gc_speed = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"car_gc_speed", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_gc_speed
    {
      get { return _car_gc_speed; }
      set { _car_gc_speed = value; }
    }
    private int _car_a_time = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"car_a_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_a_time
    {
      get { return _car_a_time; }
      set { _car_a_time = value; }
    }
    private int _car_drift = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"car_drift", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_drift
    {
      get { return _car_drift; }
      set { _car_drift = value; }
    }
    private int _end_time = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"end_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int end_time
    {
      get { return _end_time; }
      set { _end_time = value; }
    }
    private int _buy_time = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"buy_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int buy_time
    {
      get { return _buy_time; }
      set { _buy_time = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private int _playerId = default(int);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _starLevel = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"starLevel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int starLevel
    {
      get { return _starLevel; }
      set { _starLevel = value; }
    }
    private string _keepCards = "";
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"keepCards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string keepCards
    {
      get { return _keepCards; }
      set { _keepCards = value; }
    }
    private readonly global::System.Collections.Generic.List<ChipMessage> _chips = new global::System.Collections.Generic.List<ChipMessage>();
    [global::ProtoBuf.ProtoMember(16, Name=@"chips", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<ChipMessage> chips
    {
      get { return _chips; }
    }
  
    private int _carScore = default(int);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"carScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int carScore
    {
      get { return _carScore; }
      set { _carScore = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _hyun = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(18, Name=@"hyun", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> hyun
    {
      get { return _hyun; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CarListMessage")]
  public partial class CarListMessage : global::ProtoBuf.IExtensible
  {
    public CarListMessage() {}
    
    private int _count = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<CarMessage> _Pkg = new global::System.Collections.Generic.List<CarMessage>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Pkg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<CarMessage> Pkg
    {
      get { return _Pkg; }
    }
  
    private int _car_id = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"car_id", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int car_id
    {
      get { return _car_id; }
      set { _car_id = value; }
    }
    private int _curr_time = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"curr_time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int curr_time
    {
      get { return _curr_time; }
      set { _curr_time = value; }
    }
    private int _playerId = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}